FROM node:18-alpine

WORKDIR /app

# Copy only package.json
COPY package.json ./

# Install dependencies
RUN npm install --production

# Copy your app file
COPY app.js ./

EXPOSE 3000
CMD ["node", "app.js"]
