apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: 577811233724.dkr.ecr.us-east-1.amazonaws.com/dockerimg:latest
        ports:
        - containerPort: 80
