apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  DB_HOST: database-2.cefkc8ce8m5y.us-east-1.rds.amazonaws.com
  DB_PORT: "5432"
  DB_NAME: postgres        # default DB unless you created another
  DB_USER: postgres        # default master username
  DB_PASSWORD: Shiwam123
